// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDakOFa2kR-DyvKoRnz1oqitxuVLCcid_c',
    appId: '1:1046911156481:web:2629ba23c744df84609b00',
    messagingSenderId: '1046911156481',
    projectId: 'roshetta-pro-app',
    authDomain: 'roshetta-pro-app.firebaseapp.com',
    storageBucket: 'roshetta-pro-app.appspot.com',
    measurementId: 'G-PJTJN84MJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4GtI9ae3Ix0E5SHvZnDEkOXAx5Z6Pitk',
    appId: '1:1046911156481:android:0be07750e5898896609b00',
    messagingSenderId: '1046911156481',
    projectId: 'roshetta-pro-app',
    storageBucket: 'roshetta-pro-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCxBz0bC3UM_3ULAVX8wrCZNBeMghEQm0',
    appId: '1:1046911156481:ios:3bb144ea49ba13d5609b00',
    messagingSenderId: '1046911156481',
    projectId: 'roshetta-pro-app',
    storageBucket: 'roshetta-pro-app.appspot.com',
    iosBundleId: 'com.abdalla.roshettaPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCxBz0bC3UM_3ULAVX8wrCZNBeMghEQm0',
    appId: '1:1046911156481:ios:3bb144ea49ba13d5609b00',
    messagingSenderId: '1046911156481',
    projectId: 'roshetta-pro-app',
    storageBucket: 'roshetta-pro-app.appspot.com',
    iosBundleId: 'com.abdalla.roshettaPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDakOFa2kR-DyvKoRnz1oqitxuVLCcid_c',
    appId: '1:1046911156481:web:90c5dd40d7cb17a3609b00',
    messagingSenderId: '1046911156481',
    projectId: 'roshetta-pro-app',
    authDomain: 'roshetta-pro-app.firebaseapp.com',
    storageBucket: 'roshetta-pro-app.appspot.com',
    measurementId: 'G-28109BERQS',
  );
}
